// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viral2Anime.Data;

#nullable disable

namespace Viral2Anime.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911031837_AddOutputSettings")]
    partial class AddOutputSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Viral2Anime.Models.Project.ViralProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimatedClipsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimationStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FinalVideoFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FramesPerSecond")
                        .HasColumnType("REAL");

                    b.Property<string>("GeneratedKeyframesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAudio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputResolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceFramesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoryboardJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ViralProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
